In [8]:
import numpy as np

In [12]:
a=np.array([[1,2,3],[1,2,3]])

In [13]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
a[0][2]

3

In [19]:
b=np.array([3,4,5,6,7,8],dtype=float)

In [20]:
b.dtype

dtype('float64')

In [21]:
b

array([ 3.,  4.,  5.,  6.,  7.,  8.])

In [23]:
b.min()

3.0

In [25]:
c=np.zeros((2,4))

In [26]:
c

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [27]:
np.linspace(1,5,10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [28]:
np.arange(1,5)

array([1, 2, 3, 4])

In [29]:
np.rang

AttributeError: 'module' object has no attribute 'range'

In [31]:
a.ravel()

array([1, 2, 3, 1, 2, 3])

In [33]:
help(np.dot)

Help on built-in function dot in module numpy.core.multiarray:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays.
    
    For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
    arrays to inner product of vectors (without complex conjugation). For
    N dimensions it is a sum product over the last axis of `a` and
    the second-to-last of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : ndarray, optional
        Output argument. This must have the exact kind that would be returned
        if it was not used. In particular, it must have the right type, must be
        C-contiguous, and its dtype must be the dtype that would be returned
        for `dot(a,b)`. This is a performance feature. Therefore, if these
        conditions are not met, an exception is raised, instead of attempting
        to be flex

In [37]:
a[1][1]

2

In [38]:
c=np.zeros((5,5))

In [39]:
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [45]:
i=0
j=4
c[i][j]=5

In [46]:
c[i][j]

5.0

In [47]:
c

array([[ 0.,  0.,  0.,  0.,  5.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])