In [9]:
import numpy as np


In [12]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
c=np.dot(a, b)
#array([[4, 1],[2, 2]])

In [13]:
c

array([[4, 1],
       [2, 2]])

In [14]:
a

array([[1, 0],
       [0, 1]])

In [15]:
b

array([[4, 1],
       [2, 2]])

In [16]:
a+b

array([[5, 1],
       [2, 3]])

In [17]:
a/b

array([[0, 0],
       [0, 0]])

In [18]:
a-b

array([[-3, -1],
       [-2, -1]])

In [22]:
d= np.array([[1, 0], [0,0]])

In [24]:
e= np.array([[1, 0,1], [0, 1,1]])

In [25]:
e

array([[1, 0, 1],
       [0, 1, 1]])

In [26]:
d+e

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [30]:
help(arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [31]:
x= np.arange(16).reshape(4,4)

In [32]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
x=x.reshape(3,5)

ValueError: cannot reshape array of size 16 into shape (3,5)

In [35]:
for row in x:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [36]:
for cell in x:
    print(cell)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [38]:
for row in x:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [43]:
x=x.flatten()

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
help(nditer)

Help on class nditer in module numpy:

class nditer(__builtin__.object)
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  flags : sequence of str, optional
 |      Flags to control the behavior of the iterator.
 |  
 |        * "buffered" enables buffering when required.
 |        * "c_index" causes a C-order index to be tracked.
 |        * "f_index" causes a Fortran-order index to be tracked.
 |        * "multi_index" causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * "common_dtype" causes all the operands to be converted to
 |          a common data type, with copying or buffering as necessary.
 |        * "copy_if_overlap" causes the iterator to determine if read
 |  

In [46]:
x= np.arange(16).reshape(4,4)

In [53]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
for z in np.nditer(x,op_flags=["readwrite"]):
    z[...]=z*z

In [59]:
x

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])