In [1]:
import numpy as np

In [2]:
#with list
a=[1,2,3]

In [3]:
a[0:2]

[1, 2]

In [4]:
a[-1]

3

In [5]:
a[-2]

2

In [6]:
#with array
b=np.array([1,2,3])

In [7]:
b[0:2]

array([1, 2])

In [8]:
b[-1]

3

In [9]:
b[-2]

2

In [10]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
c[1,2]

6

In [13]:
c[0:2,2]

array([3, 6])

In [14]:
c[-1]

array([7, 8, 9])

In [15]:
c[-1,0:2]

array([7, 8])

In [16]:
c[:,1:3] #all rows but 1 and 2 column

array([[2, 3],
       [5, 6],
       [8, 9]])

In [23]:
#stacking
x=np.arange(6).reshape(3,2)

In [24]:
y=np.arange(6,12).reshape(3,2)

In [25]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
y

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
np.vstack((x,y))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
np.hstack((x,y))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [30]:
#splitting
z=np.arange(30).reshape(2,15)

In [31]:
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [33]:
result=np.hsplit(z,3)

In [34]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [35]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [36]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [41]:
result=np.vsplit(z,2)

In [42]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [44]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
#expressions
a=np.arange(12).reshape(3,4)

In [46]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [49]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [50]:
a[b]=-1

In [51]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])